name: Set chart version to current tag
description: Set chart version to current tag
inputs:
  test_path:
    description: 'The path to the test directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: set chart version
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh  
      env:
        TEST_PATH: ${{ inputs.test_path }}