{{- define "helm-library.statefulset.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  serviceName: {{ .Values.name }}
  selector:
    matchLabels:
      {{- include "helm-library.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- if .Values.azureIdentity }}
        aadpodidbinding: {{ required (printf $requiredMsg "name") .Values.name }}-identity-selector
        {{- end }}
        {{- include "helm-library.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.deployment.injectLinkerd }}
        linkerd.io/inject: enabled
        {{- end }}
        redeployOnChange: {{ randAlphaNum 5 | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount }}
      {{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- end }}
      {{- end }}
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | default "{}" | nindent 8 }}
      volumes:
      - name: temp-dir
        emptyDir: {}
      {{- with .Values.deployment.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      -
{{ include "helm-library.container.tpl" . | indent 8 }}
{{- end }}
{{- define "helm-library.statefulset" -}}
{{- include "helm-library.util.merge" (append . "helm-library.statefulset.tpl") -}}
{{- end -}}
