{{- define "helm-library.configmap.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required (printf $requiredMsg "configmap.name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
data: {}
{{- end }}
{{- define "helm-library.configmap" -}}
{{- include "helm-library.util.merge" (append . "helm-library.configmap.tpl") -}}
{{- end -}}
