{{- define "helm-library.cron-job.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  schedule: {{ required (printf $requiredMsg "cronJob.schedule") .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ required (printf $requiredMsg "cronJob.concurrencyPolicy") .Values.cronJob.concurrencyPolicy | quote }}
  jobTemplate: 
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.cronJob.restartPolicy | default "Always" | quote }}
          securityContext:
            fsGroup: {{ .Values.cronJob.runAsUser | default 1000 }}
            runAsUser: {{ .Values.cronJob.runAsUser | default 1000 }}
            runAsNonRoot: {{ .Values.cronJob.runAsNonRoot | default true }}
          volumes:
          - name: temp-dir
            emptyDir: {}
          containers:
          -
{{ include "helm-library.container.tpl" . | indent 12 }}
{{- end }}
{{- define "helm-library.cron-job" -}}
{{- include "helm-library.util.merge" (append . "helm-library.cron-job.tpl") -}}
{{- end -}}
