{{- define "helm-library.cron-job.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  schedule: {{ required (printf $requiredMsg "cronJob.schedule") .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ required (printf $requiredMsg "cronJob.concurrencyPolicy") .Values.cronJob.concurrencyPolicy | quote }}
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
          -
{{ include "helm-library.container.tpl" . | indent 10 }}
{{- end }}
{{- define "helm-library.cron-job" -}}
{{- include "helm-library.util.merge" (append . "helm-library.cron-job.tpl") -}}
{{- end -}}
