{{- define "helm-library.ingress.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{  required (printf $requiredMsg ".ingress.class") .Values.ingress.class | quote }}
    {{- if eq .Values.ingress.class "nginx" }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{- end }}
spec:
  {{- if .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    - www.{{ .Values.ingress.host }}
    secretName: {{ .Values.name }}-tls
  {{- end }}
  rules:
{{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
            port:
              number: {{ required (printf $requiredMsg "service.port") .Values.service.port }}
{{- if .Values.ingress.host }}
  - host: www.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
            port:
              number: {{ required (printf $requiredMsg "service.port") .Values.service.port }}
{{- end }}
{{- end }}
{{- define "helm-library.ingress" -}}
{{- include "helm-library.util.merge" (append . "helm-library.ingress.tpl") -}}
{{- end -}}

