name: "Helm Chart PR test"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install ASDF
        uses: asdf-vm/actions/setup@v3
      - name: Install ASDF plugins
        run: |
          if [ -f .tool-repos ]; then
            cat .tool-repos | while read tool || [[ -n $tool ]]; do
              echo "this line: $tool"
              echo "asdf plugin add $(echo $tool | cut -d ' ' -f 1) $(echo $tool | cut -d ' ' -f 2)"
              asdf plugin add $(echo $tool | cut -d ' ' -f 1) $(echo $tool | cut -d ' ' -f 2)
            done
          fi  
      - name: Install ASDF tools
        run: |
          if [ -f .tool-versions ]; then
            asdf install
          fi

      - name: Install Helm Chart dependencies
        working-directory: example/test-chart
        run: |
          helm dependencies update

      - name: Build Helm Template
        working-directory: example/test-chart
        run: |
          helm template . 

      - name: Lint Helm Chart
        working-directory: example/test-chart
        run: |
          helm template . | helm lint

      - name: Validate Helm Chart
        working-directory: example/test-chart
        run: |
          KUBEVERSION="1.26.5"
          helm template . | kubeconform -strict -summary -kubernetes-version $KUBEVERSION -exit-on-error


