name: Helm Chart Test and Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      kubeapi_version:
        description: "Kubernetes API version"
        required: true
        default: "1.26.5"

jobs:
  test:
    ## Always run tests.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install ASDF
        uses: asdf-vm/actions/setup@v3

      - name: Install ASDF plugins
        run: |
          if [ -f .tool-repos ]; then
            cat .tool-repos | while read tool || [[ -n $tool ]]; do
              asdf plugin add $(echo $tool | cut -d ' ' -f 1) $(echo $tool | cut -d ' ' -f 2)
            done
          fi  

      - name: Install ASDF tools
        run: |
          if [ -f .tool-versions ]; then
            asdf install
          fi

      - name: Install Helm Chart dependencies
        working-directory: example/test-chart
        run: |
          helm dependencies update

      - name: Build Helm Template
        working-directory: example/test-chart
        run: |
          helm template . 

      - name: Lint Helm Chart
        working-directory: example/test-chart
        run: |
          helm template . | helm lint

      - name: Validate Helm Chart
        working-directory: example/test-chart
        run: |
          WF_KUBEAPI_VERSION=${{ github.event.inputs.kubeapi_version }}
          KUBEAPI_VERSION=${WF_KUBEAPI_VERSION:-"1.26.5"}
          helm template . | kubeconform -strict -summary -kubernetes-version $KUBEAPI_VERSION -exit-on-error
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    needs: test
    environment:
      name: artifact-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"