name: Helm Chart Test and Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      kubeapi_version:
        description: "Kubernetes API version"
        required: true
        default: "1.26.5"

jobs:
  enumerate_tests:
    ## Always run tests.
    runs-on: ubuntu-latest
    outputs:
      valfiles: ${{ steps.find-values.outputs.valfiles }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: Install ASDF toolset
        uses: ./actions/.github/actions/setup_asdf

      - name: Find Values Files
        id: find-values
        working-directory: example/test-chart
        run: |
          valfiles=$(printf '['; find . -type f -regex "./values.*ya?ml" -printf '"%p",'| sed 's/,$//'; printf ']')
          echo "$valfiles"
          echo "valfiles=$valfiles" >> $GITHUB_OUTPUT
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: [enumerate_tests]
    strategy:
      matrix:
        values_file: ${{ fromJson(needs.enumerate_tests.outputs.valfiles) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: Install ASDF toolset
        uses: ./actions/.github/actions/setup_asdf
        
      - name: Run test jobs
        uses: ./actions/.github/actions/helm_test
        with:
          value_file: ${{ matrix.values_file }}
          test_path: ${{ github.env.GITHUB_WORKSPACE}}/example/test-chart
          kube_api_version: "1.26.5"

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    needs: test
    environment:
      name: artifact-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"